name: Submit your extension
description: Submit your extension to be published on the marketplace.
title: "[Submission]: "
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Hi :wave:,
        
        Speaking for the whole @docker/extensions, thank you for creating an extension and submitting it!
        
        The submission process is almost automatic. Once you have filled the following form and submitted this issue, some automatic validations will run.
        
        :+1: If everything goes well, a new label `validation/successful` will be added and the @docker/extensions 
        will be pinged. Later, someone from the team will add the `review/ok` which, depending if you chose a manual 
        review or not, will either 
        - trigger an automatic job to publish the extension on the marketplace
        - start our manual review process by the Docker Extension team
        
        :warning: Requesting a manual review will delay the publication of your extension on the marketplace as we 
        will play around with it and make sure it works as expected.
        
        :confused: If there are some issues, we will add the problems as comment and close the issue. Once you have fixed all the problems,
        re-open the issue and the process will start over.
  - type: input
    attributes:
      label: Docker Hub repository name
      description: Provide the Docker Hub repository name for your extension so that we can install it.
      placeholder: docker/resource-usage-extension
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        :warning: We automatically validate the greatest [semver](https://semver.org/) tag available on Docker Hub. See [the documentation](https://docs.docker.com/desktop/extensions-sdk/extensions/DISTRIBUTION/#release-your-extension) for more details.
  - type: dropdown
    attributes:
      description: Do you want Docker extension team to manually review your extension before it is published on the marketplace?
      options:
        - No
        - Yes
  - type: checkboxes
    attributes:
      label: Terms of services
      description: To submit your extension you need to accept our term of services
      options:
        - label: I am the author of the extension I submit and I have read and accept the [term of services](https://www.docker.com/legal/extensions_marketplace_developer_agreement/)
    validations:
      required: true
