on:
  workflow_dispatch:


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: ls -als /tmp
      - run: docker run -v /tmp:/foo -w /foo alpine touch hello.txt
      - run: docker run -v /tmp:/foo -w /foo alpine mkdir bar
      - run: docker run -v /tmp:/foo -w /foo alpine touch bar/hello-bar.txt
      - run: ls -als /tmp
      - run: ls -als /tmp/bar