on:
  workflow_dispatch:


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: mkdir /tmp/foo
      - run: ls -als /tmp
      - run: docker run -v /tmp/foo:/foo -w /foo alpine touch hello.txt
      - run: ls -als /tmp/foo