name: TOS Check

on:
  issues:
    types:
      - opened
      - reopened
      - edited

env:
  GH_TOKEN: ${{ github.token }}
  GH_REPO: ${{ github.repository }}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.issue.number }}
  cancel-in-progress: true

jobs:
  check:
    name: Ensure Terms of Service are accepted
    runs-on: ubuntu-latest
    permissions:
      issues: write
    outputs:
        accepted: ${{ steps.are_tos_accepted.outputs.accepted }}
    steps:
      - name: Parse issue body
        id: parse
        uses: zentered/issue-forms-body-parser@v1.5.1

      - name: Find TOS checkbox state
        id: are_tos_accepted
        run: |
          echo "accepted=$(echo '${{ steps.parse.outputs.data }}' | jq -r '.["terms-of-services"].list[0].checked' )" >> $GITHUB_OUTPUT

      - name: Remove 'tos/accepted' label
        if: steps.are_tos_accepted.outputs.accepted == 'false'
        run: gh issue edit ${{ github.event.issue.number }} --remove-label tos/accepted

      - name: Add 'tos/accepted' label
        if: steps.are_tos_accepted.outputs.accepted == 'true'
        run: gh issue edit ${{ github.event.issue.number }} --add-label tos/accepted

      - name: Add Comment if tos not accepted
        if: steps.are_tos_accepted.outputs.accepted == 'false'
        uses: peter-evans/create-or-update-comment@v2
        with:
          edit-mode: replace
          issue-number: ${{ github.event.issue.number }}
          body: |
            :x: Terms of Service not accepted yet

            ---
            See [action](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) for more details.

      - name: Add Comment if tos accepted
        if: steps.are_tos_accepted.outputs.accepted == 'true'
        uses: peter-evans/create-or-update-comment@v2
        with:
          edit-mode: replace
          issue-number: ${{ github.event.issue.number }}
          body: |
            :white_check_mark: @${{ github.event.issue.user.login}} has accepted the terms of service

            ---
            See [action](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) for more details.

      - name: Add comment if tos not found
        if: steps.are_tos_accepted.outputs.accepted == 'null'
        uses: peter-evans/create-or-update-comment@v2
        with:
          edit-mode: replace
          issue-number: ${{ github.event.issue.number }}
          body: |
            :no_entry_sign: Can't find the checkbox for the terms of service. Please add it to the issue body.

            ---
            See [action](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) for more details.

  validate:
    name: Extension validation
    needs: check
    uses: ./.github/workflows/validation.yaml
