name: Extension validation

on:
  issues:
    types:
      - labeled
      - unlabeled

concurrency:
  group: ${{ github.workflow }}-${{ github.event.issue.number }}
  cancel-in-progress: true

jobs:
  validate:
    runs-on: macOS-latest
    if: |
      contains(github.event.issue.labels.*.name, 'tos/accepted')
      && contains(github.event.issue.labels.*.name, 'validation/succeeded') == false
    steps:
      - name: Find eventual initial comment
        uses: peter-evans/find-comment@v2.1.0
        id: fc
        continue-on-error: true
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: ${{ github.workflow}} workflow has started
          direction: last

      - name: Add initial comment
        id: initial-comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            [${{ github.workflow}}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) workflow has started.
          edit-mode: replace

      - name: Get Date
        id: get-date
        run: |
          echo "::set-output name=date::$(/bin/date -u "+%Y%m%d")"
        shell: bash

      - name: Redirect api.segment.io to localhost
        id: redirect-segment
        run: |
          echo '127.0.0.2 api.segment.io' | sudo tee -a /etc/hosts
          cat /etc/hosts

      - name: Get Docker app cache
        id: cache-docker-desktop-app
        uses: actions/cache@v3
        env:
          cache-name: cache-docker-desktop-app
        with:
          path: /Applications/Docker.app
          key: docker-desktop-app-mac-amd64-${{ steps.get-date.outputs.date }}

      - name: Get Docker install settings cache
        id: cache-docker-desktop-install-settings
        uses: actions/cache@v3
        env:
          cache-name: cache-docker-desktop-install-settings
        with:
          path: ./cache/desktopInstallSettings/
          key: docker-desktop-install-settings-mac-${{ steps.get-date.outputs.date }}

      - name: Copy Desktop install settings in /Library
        if: steps.cache-docker-desktop-install-settings.outputs.cache-hit == 'true'
        run: |
          echo "ls ./cache/desktopInstallSettings/"
          ls ./cache/desktopInstallSettings/
          sudo mkdir -p "/Library/Application Support/com.docker.docker"
          sudo cp ./cache/desktopInstallSettings/* "/Library/Application Support/com.docker.docker/"
          echo "/Library/Application Support/com.docker.docker/"
          ls "/Library/Application Support/com.docker.docker/"

      - name: Fetch and install Docker Desktop dmg
        if: steps.cache-docker-desktop-install-settings.outputs.cache-hit != 'true'
        run: |
          sw_vers
          mkdir ./temp
          mkdir ./mount
          wget -q -O ./temp/DockerDesktop.dmg https://desktop.docker.com/mac/main/amd64/Docker.dmg
          /usr/bin/hdiutil attach -noverify ./temp/DockerDesktop.dmg -mountpoint ./mount/desktop -nobrowse
          echo "dmg mounted"
          sudo ./mount/desktop/Docker.app/Contents/MacOS/install --accept-license
          echo "dmg installed"
          echo "ls /Library/Application Support/com.docker.docker"
          ls "/Library/Application Support/com.docker.docker" || true
          mkdir -p ./cache/desktopInstallSettings
          cp "/Library/Application Support/com.docker.docker/"* ./cache/desktopInstallSettings/
          echo "ls ./cache/desktopInstallSettings/"
          ls ./cache/desktopInstallSettings/ || true
          /usr/bin/hdiutil detach ./mount/desktop
          echo "dmg unmounted"

      - name: Start Docker Desktop
        timeout-minutes: 5
        run: |
          sudo /Applications/Docker.app/Contents/MacOS/install config --user runner
          sudo mkdir /Library/PrivilegedHelperTools
          sudo /Applications/Docker.app/Contents/MacOS/install vmnetd
          echo "app installed"
          /usr/bin/open /Applications/Docker.app --args --unattended --add-host-docker-internal-registry
          echo "Docker starting..."

      - name: Wait for Docker to be up and running
        timeout-minutes: 5
        run: |
          until docker ps; do echo "ps failed, sleep 10 s and try again"; sleep 10; done
          echo "Docker started and ready"

      - name: Parse issue body
        id: parse
        uses: zentered/issue-forms-body-parser@v1.5.1

      - name: Find extension repository
        id: parse-repository
        run: |
          echo "repository=$(echo '${{ steps.parse.outputs.data }}' | jq -r '.["docker-hub-repository-name"].text' )" >> $GITHUB_OUTPUT

      - name: Validate extension
        id: validate
        run: |
          touch output.txt
          docker extension validate ${{ steps.parse-repository.outputs.repository }} &> output.txt
          echo 'VALIDATION_OUTPUT<<EOF' >> $GITHUB_ENV
          cat output.txt >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

      - name: Add Comment if validation succeeded
        if: ${{ contains(env.VALIDATION_OUTPUT, 'passes the validation checks.') }}
        uses: peter-evans/create-or-update-comment@v2
        with:
          edit-mode: replace
          issue-number: ${{ github.event.issue.number }}
          comment-id: ${{ steps.initial-comment.outputs.comment-id }}
          body: |
            :white_check_mark: Validation ended successfully

            > ${{ env.VALIDATION_OUTPUT }}

            See [${{ github.workflow}}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}).

      - name: Add 'validation/succeed' label
        if: ${{ contains(env.VALIDATION_OUTPUT, 'passes the validation checks.') }}
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["tos/accepted"]
            })

      - name: Add Comment if validation failed
        if: ${{ contains(env.VALIDATION_OUTPUT, 'passes the validation checks.') == false }}
        uses: peter-evans/create-or-update-comment@v2
        with:
          edit-mode: replace
          issue-number: ${{ github.event.issue.number }}
          comment-id: ${{ steps.initial-comment.outputs.comment-id }}
          body: |
            :x: Validation failed with the following errors

            > ${{ env.VALIDATION_OUTPUT }}

            See [${{ github.workflow}}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}).

      - name: Add Comment if job failed
        if: ${{ failure() }}
        uses: peter-evans/create-or-update-comment@v2
        with:
          edit-mode: replace
          issue-number: ${{ github.event.issue.number }}
          comment-id: ${{ steps.initial-comment.outputs.comment-id }}
          body: |
            :x: There was a problem during the validation job

            See [${{ github.workflow}}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}).

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        timeout-minutes: 10